failing test

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -58,48 +58,47 @@ jobs:
           restore-keys: |
             ccache-${{ secrets.CACHE_VERSION }}-${{ steps.prepare-ccache.outputs.key }}-
 
-      - name: Run benchmarks
-        shell: bash -l {0}
-        id: benchmark
-        env:
-          OPENBLAS_NUM_THREADS: 1
-          MKL_NUM_THREADS: 1
-          OMP_NUM_THREADS: 1
-          ASV_FACTOR: 1.5
-          ASV_SKIP_SLOW: 1
-        run: |
-          set -x
+      # - name: Run benchmarks
+      #   shell: bash -l {0}
+      #   id: benchmark
+      #   env:
+      #     OPENBLAS_NUM_THREADS: 1
+      #     MKL_NUM_THREADS: 1
+      #     OMP_NUM_THREADS: 1
+      #     ASV_FACTOR: 1.5
+      #     ASV_SKIP_SLOW: 1
+      #   run: |
+      #     set -x
 
-          python -m pip install virtualenv
+      #     python -m pip install virtualenv
 
-          # ID this runner
-          asv machine --yes
+      #     # ID this runner
+      #     asv machine --yes
 
-          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
-          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"
+      #     echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
+      #     echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"
 
-          # Run benchmarks for current commit against base
-          ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR"
-          asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
-              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
-              | tee benchmarks.log
+      #     # Run benchmarks for current commit against base
+      #     ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR"
+      #     asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
+      #         | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
+      #         | tee benchmarks.log
 
-          # Report and export results for subsequent steps
-          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
-              exit 1
-          fi
+      #     # Report and export results for subsequent steps
+      #     if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
+      #         exit 1
+      #     fi
 
       - name: "Check ccache performance"
         shell: bash -l {0}
         run: ccache -s
         if: always()
 
-      - name: Add instructions to artifact
-        if: always()
-        run: cp benchmarks/README_CI.md benchmarks.log .asv/results/
-
+      # - name: Add instructions to artifact
+      #   if: always()
+      #   run: cp benchmarks/README_CI.md benchmarks.log .asv/results/
       - uses: actions/upload-artifact@v3
-        if: always()
-        with:
-          name: asv-benchmark-results-${{ runner.os }}
-          path: .asv/results
+        # if: always()
+        # with:
+        #   name: asv-benchmark-results-${{ runner.os }}
+        #   path: .asv/results
